---

- name: Push the latest updates to Ubuntu Servers
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    only_upgrade: true

- name: Clean the Ubuntu Servers
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    purge: true
