---

- name: Update all packages for RHEL Servers through Satellite using Job Invoction
  theforeman.foreman.job_invoction:
    server_url: https://{{ redhat_satellite_server }}
    username: "{{ redhat_satellite_user }}"
    password: "{{ redhat_satellite_password }}"
    job_tempalte: "Package Action - Script Default"
    search_query: "{{ redhat_satellite_job_search_query }}"
    inputs: "action=update,package=' '"
  when:
    - patch_rhel_by == 'satellite-job'

- name: Patch RHEL using Hammer
  when:
    - patch_rhel_by == 'satellite-hammer'
  block:
    - name: Check Hammer is configured
      ansible.builtin.command:
        cmd: hammer auth status
      register: hammer_auth_status
      changed_when: false

    - name: Hammer is not configured
      ansible.builtin.fail:
        msg: "Hammer is not configured. Please configure it first."
      when:
        - "'Credentials are not configured' in hammer_auth_status.stdout"

    - name: Update all packages for RHEL Servers through Satellite using Hammer
      ansible.builtin.command: >-
        hammer job-invocation create --organization {{ redhat_satellite_organization_name }}
        --job-template "Package Action - Script Default"
        --search-query {{ redhat_satellite_job_search_query }}
        --inputs action=update,package=' '
      delegate_to: "{{ redhat_satellite_server }}"
      register: hammer_job_invocation_create
      changed_when: hammer_job_invocation_create.rc == 0
      async: 600
      poll: 10

- name: Update all packages for RHEL Servers
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
    update_cache: true
  when:
    - patch_rhel_by == 'yum'
