---

- name: Push the latest updates to Ubuntu Servers
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
    update_cache: true

- name: Clean the Ubuntu Servers
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    purge: true
