---

- name: Verify limit is set
  ansible.builtin.fail:
    msg: 'This playbook cannot be run with no limit'
  run_once: true
  when:
    - enforce_using_limit == 'yes'
    - ansible_limit is not defined

- name: Google Connection and Data Collection
  delegate_to: localhost
  block:
    - name: Get Access Token
      ansible.builtin.uri:
        url: https://accounts.google.com/o/oauth2/token
        method: POST
        body_format: json
        body:
          client_id: "{{ google_client_id }}"
          client_secret: "{{ google_client_secret }}"
          refresh_token: "{{ google_refresh_token }}"
          grant_type: refresh_token
      register: token

    - name: Assign Access Token to a Variable
      ansible.builtin.set_fact:
        access_token: "{{ token.json.access_token }}"

    - name: Get Data From Google Spreadsheet
      ansible.builtin.uri:
        url: "{{ google_sheet_api_url }}/{{ google_sheet_id }}/values/{{ google_sheet_name }}!{{ google_sheet_range }}?majorDimension=ROWS"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: application/json
      register: google_data
