---

- name: Configure Nagios Downtime
  delegate_to: "{{ nagios_server }}"
  block:
    - name: Schedule a Downtime on NagiOS for {{ hostname }}
      community.general.nagios:
        action: downtime
        minutes: "{{ nagios_downtime_in_minutes }}"
        service: host
        host: "{{ hostname }}"
        comment: "{{ nagios_downtime_comment }}"

    - name: Schedule Services Downtime on NagiOS for {{ hostname }}
      community.general.nagios:
        action: downtime
        minutes: "{{ nagios_downtime_in_minutes }}"
        service: all
        host: "{{ hostname }}"
        comment: "{{ nagios_downtime_comment }}"
