---
# tasks file for os_patching

- name: Pre-tasks
  ansible.builtin.include_tasks:
    file: pre_tasks.yml

- name: Disable Monitoring
  ansible.builtin.include_tasks:
    file: disable_monitoring.yml
  when: nagios_schedule_downtime

- name: Update Status to Downtime-Scheduled
  ansible.builtin.include_tasks:
    file: update_status.yml
  vars:
    status: "Downtime-Scheduled"

- name: Update Status to Patching
  ansible.builtin.include_tasks:
    file: update_status.yml
  vars:
    status: "Patching"

- name: Patch RHEL Servers
  ansible.builtin.include_tasks:
    file: patch_rhel.yml
  when: ansible_distribution == 'RedHat'

- name: Patch Ubuntu Servers
  ansible.builtin.include_tasks:
    file: patch_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Patch Windows Servers
  ansible.builtin.include_tasks:
    file: patch_windows.yml
  when: ansible_os_family == 'Windows'

- name: Reboot Hosts
  ansible.builtin.include_tasks:
    file: reboot.yml

- name: Update Status to Patched
  ansible.builtin.include_tasks:
    file: update_status.yml
  vars:
    status: "Patched"
