---

- name: Check if there is a pending reboot
  ansible.windows.win_command: Powershell.exe "Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired'"
  register: reboot_required
  changed_when: false

- name: Clear pending reboot
  ansible.windows.win_reboot:
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  when:
    - "'True' in reboot_required.stdout_lines"

- name: Ensure log file exists
  ansible.windows.win_file:
    path: "{{ windows_update_log_file }}"
    state: touch

- name: Install Windows Online updates (if any)
  ansible.windows.win_updates:
    server_selection: "{{ windows_update_server_selection }}"
    category_names: '*'
    state: installed
    reboot: true
    reject_list: "{{ windows_update_reject_list }}"
    log_path: "{{ windows_update_log_file }}"
  register: winonline_installed_updates

- name: Print Updates Status
  ansible.builtin.debug:
    var: winonline_installed_updates.updates
