---

- name: Update Host Status in Google Sheet to {{ status }}
  ansible.builtin.uri:
    url: "{{ google_sheet_api_url }}/{{ google_sheet_id }}/values/{{ google_sheet_name }}!{{ google_sheet_status_column }}{{ host_index }}?valueInputOption=RAW"
    method: PUT
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: application/json
    body_format: json
    body: |
      {
        "range": "{{ google_sheet_name }}!{{ google_sheet_status_column }}{{ host_index }}",
        "majorDimension": "ROWS",
        "values": [["{{ status }}"]]
      }
  vars:
    host_index: >-
      {{ lookup('ansible.utils.index_of',
      google_data | community.general.json_query('json.values[*]'), 'eq',
      google_data | community.general.json_query('json.values[?contains(@, `' + ansible_hostname + '`)] | [0]')) + 2 | default(-1) }}
    host_data: "{{ google_data | community.general.json_query('json.values[?contains(@, `' + ansible_hostname + '`)] | [0]') | default(-1) }}"
  when: ansible_hostname in host_data
  register: response_status
  changed_when: response_status.json.updatedCells > 0
  delegate_to: localhost
